### PR TITLE
Adding a 'jobsub' command to list available commands

### LINKED ISSUE #471: Add a "jobsub -h" option to list all jobsub commands
A request from Heidi Schellman in RITM1845157

Users often don't know which jobsub commands exist.  If there were a jobsub -h (or even jobsub ) that just listed the jobsub commands, that would be very helpful.  Bonus points for having it point to a url for the real documentation.

### PR DESCRIPTION
**Pull request by marcmengel**
It's pretty much more documentation than code, but here it is.

Closes #471

### CODE REVIEW

**Comment by shreyb** [comment]
Converted to draft so we can discuss this at the next Developers meeting on Aug 30, 2023.

**Review by retzkek — CHANGES_REQUESTED** [review]
I'd like to see one-line descriptions of the commands here. This may also be a good place for a list of environment variables that affect how jobsub operates.

Also I'd like us to consider (not necessarily implement here) a refactor of jobsub to the common subcommand pattern, e.g. `jobsub_submit ...` becomes `jobsub submit ...` (with a compatibility alias), which would make sure that the list of (sub-)commands and their descriptions don't stray from what's actually implemented, and would help ensure uniformity between them. Maybe we include the wrapped condor commands too, e.g. `jobsub condor_q ...`.

This is important to discuss now as it could impact how this "quick fix" script works, to make sure that it won't become a future breaking change.

**Comment by marcmengel** [comment]
So, I've added a brief description to the jobsub commands,and minimal command line flag information.
and (some) environment variables; this ramps us up to two and a half screenfuls of description...
I am concerned this is a little too much information for an overview...

**Comment by marcmengel** [comment]
So, looking at the master "jobsub" command idea again... If we took the existing
main() functions in the the 4 main jobsub scripts
jobsub_cmd
jobsub_fetchlog
jobsub_history
jobsub_submit
(the rest are all symlinks...) 
and split them into 2 parts -- 1 that adds arguments to the parser, and 1 that
implements the script logic, we could then have standalone scripts which 
would be pretty much:

if __name__ == '__main__':
       parser = argparser.ArgumentParser
       parsr = this_command_get_parser(parser=parser)

**Pull request merged**
