### PR TITLE
Adding Fermitools license file

### PR DESCRIPTION
**Pull request by marcmengel**

### CODE REVIEW

**Review by shreyb — CHANGES_REQUESTED** [review]
Is that filename supposed to be COPYRIGHT rather than COPYING?

**Comment by shreyb** [comment]
And should that be "LICENSE"?  I can't remember what the Fermilab rules are off the top of my head.

**Comment by marcmengel** [comment]
So I checked my email logs; Aaron recommended an Apache 2.0 license for this; so yes, that one generally goes in a LICENSE file.  So I dropped the other one, and added this one.

**Comment by marcmengel** [comment]
Hang on, re-read the notes...

**Review by shreyb — APPROVED** [review]

**Pull request merged**
