### PR TITLE
clear mtime on -f dropbox: tarfile creation.

### PR DESCRIPTION
**Pull request by marcmengel**
This is a redo of #397, which got all funky when I tried to rebase it...

### CODE REVIEW

**Comment by shreyb** [comment]
Just wanted to note here that we _do_ have experiment signoff to implement this.

**Comment by marcmengel** [comment]
So put files of the same name & contents in different directories, and try that.

**Comment by shreyb** [comment]
....that's so obvious I can't believe I didn't catch that myself.  Thanks, Marc.  I'll retest.

**Comment by shreyb** [comment]
This looks good.  I reran my test above:


### Try this again:


#### With jobsub_lite 1.3.3:

tarball 1: 
- Command: `jobsub_submit -G fermilab -f dropbox:///home/sbhat/uboone_tar_tests_jobsub_lite/dir1/jobsub_lite_test.tar -n --debug file:///usr/bin/sleep 300`
- Hash:  `fermilab/938795603747c56daf5f71e42251a203c815a73a95284bf9172e73e8e9d14559`

tarball 2:
- Command: `jobsub_submit -G fermilab -f dropbox:///home/sbhat/uboone_tar_tests_jobsub_lite/dir2/jobsub_lite_test.tar -n --debug file:///usr/bin/sleep 300`
- Hash: `fermilab/ea11610900e96fecb71b6b82ec44b9247890c812e6d9d088ef211ef32f0d3c8e`


#### With PR 431:

tarball 1: `fermilab/85c3f950e2b3042e1096664ff90c7244d01bfec581a86ee222e82d11d958b5ad`
tarball 2: `fermilab/85c3f950e2b3042e1096664ff90c7244d01bfec581a86ee222e82d11d958b5ad`


Going to check unit tests before approving.

**Comment by shreyb** [comment]
Unit tests pass.  This is good to go.

**Review by shreyb — APPROVED** [review]

**Pull request merged**
