### PR TITLE
Update cvmfs_info function

### PR DESCRIPTION
**Pull request by vitodb**
Address issue #574
Extend the use of cvmfs_info function to osgstorage repos alongside opensciencegrid repos
For SBND and ICARUS check also SBN CVMFS repos

### CODE REVIEW

**Review by marcmengel — APPROVED** [review]
Looks good.

**Comment by marcmengel** [comment]
This is a good idea ; should we also, for suitable experiments, be checking larsoft.opensciencegrid.org as well?

**Comment by vitodb** [comment]
> This is a good idea ; should we also, for suitable experiments, be checking larsoft.opensciencegrid.org as well?

I thought of this, but because for larsoft CVMFS repo we don't have the osgstorage repo I left this over.
However adding an extra check to exclude osgstorage, we can test also larsoft for suitable experiments.

**Comment by vitodb** [comment]
I have included the check of larsoft CVMFS repo as suggested by Marc, alongside few other improvements.

**Comment by shreyb** [comment]
@marcmengel I'll hold off on merging for a couple of days in case you wanted to check Vito's latest commit.

**Review by marcmengel — COMMENTED** [review]
Looks good!  I like the conditional larsoft check...

**Review by marcmengel — APPROVED** [review]

**Pull request merged**
