### PR TITLE
Updating condor_vault_storer

### PR DESCRIPTION
**Pull request by marcmengel**
Latest from @DrDaveD .   Implements #544 .

### CODE REVIEW

**Comment by marcmengel** [comment]
Still waiting for integration tests to complete...

**Comment by marcmengel** [comment]
Okay, integration tests look good.   There is a problem with test_condor_submit_dag1() in the integration tests (start job keeps going held due to system periodic hold) , but it also happens in the master branch without these changes, so I don't think this causes it.

**Comment by shreyb** [comment]
Note that the issue @marcmengel is referring to he fixes in #564. (Marc, please correct me if I'm mistaken about that).

**Review by shreyb — APPROVED** [review]
Looks good.  I ran the unit tests affected, and everything works.

Also, doing a diff directly on this PR's version of condor_vault_storer and the one in @DrDaveD's link in #544 , shows just the POMS clause, which is what we expect.

**Pull request merged**
